# -*- coding: utf-8 -*-
"""credit_risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ur4SRsXToOA8EFbiOyTsTl4Zq6s58IHK

# Bank Credit Risk Analysis

The objective of this project is to analyze bank credit data, perform Exploratory Data Analysis (EDA), and identify the key drivers that predict the probability of client default.

This analysis aims to provide actionable insights for risk management and credit approval processes.
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statistics as stats
import scipy
import plotly.express as px
import plotly.io as pio
import warnings

warnings.filterwarnings("ignore")

"""## Exploratory Data Analysis (EDA) & Data Profiling"""

dataset = pd.read_csv("/content/credit_risk_dataset.csv")
df = dataset.copy()

df.info()
df.shape

df.head()

# unique object values in the dataset
for col in df.select_dtypes(include="object").columns:
    print(f"{col}: {df[col].unique()}\n")

# NA values
df.isna().sum()

"""Missing values can be managed in many ways, sometimes we can just omit those observations.

We can also try to impute the mean or median value to them:
* mean: computionally easy, often bad results with outliers
* median: more stable, better choice.
"""

# median value to missing values
for col in df.select_dtypes(include="number").columns:
    df[col].fillna(df[col].median(), inplace=True)

df.isna().sum()

"""It's also important to see if our numerical variables have normal values."""

df.describe().T

"""### Data Cleaning: Handling Outliers
An age or employment length that is over 100 years is unlikely and represents a data entry error. These observations will be removed to prevent skewing the statistical analysis and models performance.

Many models (in particular those that works with distances) are affected negativly by unusual values.
"""

# drop > 100 years old
df = df[(df["person_age"] <= 100) & (df["person_emp_length"] <= 100)]

numeric_cols = df.select_dtypes(include="number").columns
corr_matrix = df[numeric_cols].corr()

px.imshow(corr_matrix,
          text_auto=True,
          aspect="auto",
          title="Correlation Matrix",
          color_continuous_scale="RdBu_r", zmin=-1, zmax=1)

"""The objective of this analysis is to describe our variables, and of course find informations about the probability that a client will go in default with his credit plan.

## Variable Descriptions

| Variable | Description | Values |
|---|---|---|
| person_age | Age of the individual applying for the loan | Numeric |
| person_income | Annual income of the individual | Numeric |
| person_home_ownership | Type of home ownership | rent, mortgage, own, other |
| person_emp_length | Employment length in years | Numeric |
| loan_intent | Intent behind the loan application | Numeric |
| loan_grade | Grade based on creditworthiness | A (low risk) to G (highest risk) |
| loan_amnt | Loan amount requested | Numeric |
| loan_int_rate | Interest rate associated with the loan | Numeric |
| loan_status | Loan default status | 0 (Non-default), 1 (Default) |
| loan_percent_income | Percentage of income represented by loan | Numeric |
| cb_person_default_on_file | Historical default on credit file | Y (yes), N (no) |
| cb_person_cred_hist_length | Length of credit history | Numeric |

### Loan Grade Scale
| Grade | Risk Level | Description |
|---|---|---|
| A | Low | High creditworthiness |
| B | Low-Medium | Relatively low-risk |
| C | Medium | Moderate creditworthiness |
| D | Medium-High | Higher risk |
| E | High | Lower creditworthiness |
| F | Very High | Significant credit risk |
| G | Highest | Lowest creditworthiness |

### Key Insights
- **loan_status** is a binary variable (0 = non-default, 1 = default)
- Positively correlated with **loan_int_rate**: higher interest rates indicate higher default probability
- Positively correlated with **loan_percent_income**: higher loan-to-income ratio indicates higher default probability

## Univariate Analysis
"""

for col in df.select_dtypes(include="object").columns:
    fig = px.histogram(df, x=col, title=f"Distribution of {col}",
                       histnorm="percent",
                       text_auto=True)
    # TEXTAUTO shows percentage values on bars


    fig.show()

fig = px.pie(df, names="loan_status", title="Distribution of Loan Status",
       color_discrete_sequence=px.colors.sequential.RdBu)

fig.update_traces(textinfo="label+value+percent", textposition="inside")
fig.show()

"""The dataset comprises a total of 32,600 observations, where 21.8% of the individuals (7,107 users) are in default."""

sns.pairplot(df, hue="loan_status", diag_kind="kde", corner=True)

"""### Outliers

Boxplots are useful to see the distribution of our observations to a specific feature, but it also allows to see if there are outliers in our dataset, identified by dots on the plot.

While some outliers may represent real-world extremes worth keeping (as they carry valuable distributional information), others (like ages >100) likely indicate data entry errors and should be removed to avoid skewing analysis.
"""

# boxplot for numeric variables
for col in df.select_dtypes(include="number").columns:
    if col == "loan_status":
        continue
    fig = px.box(df, x=col, title=f"Boxplot of {col}")
    fig.show()

"""There are numerous oultier values: we need to decide, in predictive models, if that is a problem, for each variable.

Sometimes it's reasonable to keep them in the analysis, in fact they can carry many useful informations about our dataset distribution.

A solution, that can also resolve the problem of skewness, is a logarithmic transormation of our variable:
* Compresses the scale and reduces skewness
* Particularly effective for right-skewed distributions
* Works well for income, loan amounts, and similar financial variables

`person_income` has to many outliers, in fact our boxplot is flat, we can transform its scale with logarithm.
"""

df['person_income'] = np.log(df['person_income'])
px.box(df, x="person_income", title="Boxplot of person_income")

"""## Bivariate Analysis

Here we find more informations about our data, in relation with multiple variables, to see the structure of our data in a wider view.

This stage is essential, but should be done in Power BI or similar softwares.
"""

df.head(5)

fig = px.histogram(df, x="person_age", y="loan_amnt",
                 title="Age vs Income by Loan Amount", color="loan_status",
                 color_discrete_sequence=px.colors.sequential.RdBu)
# adding mean and median lines
fig.add_vline(x=df["person_age"].mean(), line_color ="green", annotation_text="Mean", annotation_position="top right", annotation_font_color="green")
fig.add_vline(x=df["person_age"].median(), line_color ="red", annotation_text="Median", annotation_position="top left", annotation_font_color="red")

fig.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.kdeplot(data=df, x="person_age", hue="loan_status", fill=True, )
plt.title('Kernel Density Estimate of Person Age by Loan Status')
plt.xlabel('Person Age')
plt.ylabel('Density')
plt.show()

"""This is an example of a positive (right) skewness."""

# loan interest rate and loan grade, confronted with loan_status
fig = px.box(df, x="loan_grade", y = "loan_int_rate", color='loan_status', title="Loan interest rate for each category")
fig.show()

df.head(2)

# analysis between default and not default
px.box(df, x="person_home_ownership", y="person_income", color='loan_status')

# Remember -> log person_income

"""In every case, people where `loan_status` is 0 have more income than the other case, so we can assume that `person_income` is important to determine if someone is in risk of default, by looking to his income level"""

# loan_percent_income and
# analysis between default and not default
px.box(df, x="person_home_ownership", y="loan_percent_income", color='loan_status')

"""Similar results, if the loan amount is significantly higher than his income the probability of default is more likely to be high, excluding MORTGAGE, where we have similar values.

## Feature engineering

Feature engineering is a process of creating new features from existing ones to improve the performance of machine learning models. It can involve various techniques such as:
- **Creating new features**: This can be done by combining existing features, applying mathematical operations, or using domain knowledge to create new features that may be more informative for the model.

- **Encoding categorical variables**: This involves converting categorical variables into numerical format so that they can be used in machine learning models. Common techniques include one-hot encoding, label encoding, and target encoding.

- **Scaling and normalization**: This involves transforming numerical features to a common scale, which can help improve the performance of certain machine learning algorithms. Common techniques include min-max scaling, standardization, and robust scaling.
"""

df.head()

"""### Age groups"""

df["age_group"] = pd.cut(df["person_age"],
                         bins=[0, 25, 35, 45, 55, 65, 100],
                         labels=["0-25", "26-35", "36-45", "46-55", "56-65", "66+"])

df[["age_group", "person_age"]].head(15)

# put age_group column after person_age

df.insert(df.columns.get_loc("person_age") + 1, "age_group", df.pop("age_group")) # not iloc
# insert where ? - insert what? - delete previous age_group column

df.head()

"""### Income groups"""

# income groups, q3 is 80k
df["income_group"] = pd.cut(df["person_income"],
                            bins=[0, 40000, 80000, 120000, 160000, 200000, np.inf],
                            labels=["0-40k", "40k-80k", "80k-120k", "120k-160k", "160k-200k", "200k+"])

df.insert(df.columns.get_loc("person_income") + 1, "income_group", df.pop("income_group"))
df.head()

"""and so on..."""

numeric_cols = df.select_dtypes(include=[np.number])

fig = px.imshow(numeric_cols.corr(), text_auto=True, aspect="auto")
fig.show()

"""## Statistical tests

A crucial step of any statistical-based analysis is to do some tests to our data.

Chi-square test is an important test made on categorical variables, over a single objective variable, to test wether or not there is indipendency between the two.
"""

cate_cols = df.select_dtypes(include="object").columns
for col in cate_cols:
    print(f"{col}: {df[col].unique()}\n")

from scipy.stats import chi2_contingency

max = 0
for col in cate_cols:
    chi2, pvalue, dof, expected_freq = chi2_contingency(pd.crosstab(df[col], df["loan_status"])) # crosstab computes frequency of variable 1 on loan_status (0 or 1) like a pivot.

    print("--- Chi-square test ---")
    print(f"Column: {col}")
    print(f"Chi2: {chi2}")
    print(f"P-value: {pvalue}")
    if pvalue < 0.05:
        print("High statistical significativity. Reject null hypothesis (there is dependency) ")
    print("-------------\n")
    if chi2 > max:
        max = chi2
        max_col = col

print(f"The most effective / important variable (that captures majority of loan_status variance) is: {max_col} with a Chi2 value of {max}")

"""# Data preprocessing
Here we prepare our data to get used in train and test processes. So to test if our models are good enougth to classify and predict credit risk people.

The objective variable is `loan_status`, so we drop it from the dataset.

IN THIS CASE WE NEED TO ENCODE CATEGORICAL VARIABLES (ONE-HOT-ENCODING)
"""

data = df.copy()
#data = data.drop(['index'], axis=1)
#data.reset_index(inplace=True) # Inplace does not remove previous dataframe
data.head(2)

data.columns

#data = data.select_dtypes(include=(np.number))

X = data.drop(['loan_status'], axis=1)
Y = data['loan_status']

from sklearn.model_selection import train_test_split

# ORDER MATTERS
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=12)

print(X_train.shape, X_test.shape)

X_train.reset_index(inplace=True)
X_test.reset_index(inplace=True)

X_train.columns

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

#ohe includes categorical and obj type variables
cate_cols = data.select_dtypes(include=("category", "object")).columns

cate_cols

ohe.fit(X_train[cate_cols])

ohe.categories_

"""Concatenate all"""

from numpy import concatenate

merge_ohe = np.concatenate((
    ohe.categories_[0],
    ohe.categories_[1],
    ohe.categories_[2],
    ohe.categories_[3],
    ohe.categories_[4],
    ohe.categories_[5],
                            ))

merge_ohe

ohe_train = pd.DataFrame(ohe.transform(X_train[cate_cols]).toarray(),
                        columns=merge_ohe) # transform X from OHE, columns for each categorical value
ohe_test = pd.DataFrame(ohe.transform(X_test[cate_cols]).toarray(),
                        columns=merge_ohe)
ohe_train

X_train_all = pd.concat([ohe_train, X_train], axis=1).drop(cate_cols, axis=1) #drop categorical remaning

X_test_all = pd.concat([ohe_test, X_test], axis=1).drop(cate_cols, axis=1)

X_train_all.head()

X_train_all.shape

"""# Scaling process
* MinMaxScaler for uniform distributions
* StandardScaler for Normal Gaussian distributions
* RobustScaler for bimodal or with outliers distributions
"""

from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

scaler = StandardScaler()
numeric_cols = df.select_dtypes(include=np.number).columns.drop(['loan_status'], errors='ignore')

X_train_all[numeric_cols] = scaler.fit_transform(X_train_all[numeric_cols])
X_test_all[numeric_cols] = scaler.fit_transform(X_test_all[numeric_cols])

X_train_all.head(2)

# drop index column
X_train_all = X_train_all.drop(['index'], axis=1)
X_test_all = X_test_all.drop(['index'], axis=1)
Y_test = Y_test.reset_index(drop=True)
Y_train = Y_train.reset_index(drop=True)

"""# Classification Models"""

# pip install catboost
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier, XGBRFClassifier

kn = KNeighborsClassifier()
dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
log_reg = LogisticRegression()
xgb = XGBClassifier()
cbc = CatBoostClassifier(verbose = False)

mod = {
    'KN' : kn,
    'DT' : dt,
    'XGB' : xgb,
    'LogiReg' : log_reg,
    'RF' : rf,
    'CatBoostCla' : cbc
}

# function to all the classifiers
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score


def train_classifier(mod, X_train, Y_train, X_test, Y_test):

    mod.fit(X_train, Y_train)
    Y_pred = mod.predict(X_test)

    accuracy = accuracy_score(Y_test, Y_pred)
    precision = precision_score(Y_test, Y_pred)
    recall = recall_score(Y_test, Y_pred)

    # Confusion Matrix
    tn, fp, fn, tp = confusion_matrix(Y_test, Y_pred).ravel() # ravel to do / operations
    specificity = tn / (tn + fp)

    return accuracy, precision, recall, specificity

accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []

for name, model in mod.items():

    current_accuracy,current_precision, current_recall, current_specificity = train_classifier(model, X_train_all, Y_train, X_test_all, Y_test)

    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print("Specificity - ",current_specificity)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)

# Best model
models_report = pd.DataFrame({
    'Model' : list(mod.keys()),
    'Accuracy' : accuracy_scores,
    'Precision' : precision_scores,
    'Recall' : recall_scores,
    'Specificity' : specificity_scores
}).sort_values('Accuracy', ascending=False)

print(models_report)

# cbc classification report with default parameters
from sklearn.metrics import classification_report
old_classification_report = classification_report(Y_test, cbc.predict(X_test_all))
print(old_classification_report)

"""### ROC - AUC"""

# roc - auc
from sklearn.metrics import roc_auc_score, roc_curve

auc_value = {}

for name, model in mod.items():

    model.fit(X_train_all, Y_train)

    y_score = model.predict_proba(X_test_all)[:, 1] # prediction of class 1

    auc = roc_auc_score(Y_test, y_score)

    auc_value[name] = auc
    print(f'AUC for {name}: {auc}')

    fpr, tpr, thresholds = roc_curve(Y_test, y_score)

    plt.figure()
    plt.plot(fpr, tpr)
    plt.plot([0, 1], [0, 1], 'k--', linewidth=1.5, label='Baseline (Casual - AUC 0.5)')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'ROC Curve for {name}')

"""In terms of AUC value, `RF` model is the best. This means that the probability of correct guess to a True Positive is higher than a wrong guess."""

# confusion matrix of best model
from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_estimator(cbc, X_test_all, Y_test)

"""CatBoostClassifier got right 4380 + 915 observations in the training process.

Our next objective is to tune this model to improve those results, to get even better in the classification process.

For this type of dataset, that has over 28.000 observations, any tuning process based on range values (like GridSearchCV) is computionally intensive, so it's easier to do it manually by setting the parameters that we want to change from default value.

### CatBoostClassifier tuning
"""

cbc = CatBoostClassifier(
    iterations=600,
    learning_rate=0.05,
    depth=10,
    random_seed=42,
    verbose=False
 )


cbc.fit(X_train_all,
        Y_train,
        eval_set=(X_test_all, Y_test))

from sklearn.metrics import classification_report

print(classification_report(Y_test, cbc.predict(X_test_all)))
print(f'Old \n {old_classification_report}')

cbc_feature_importance = cbc.feature_importances_

feature_importance_df = pd.DataFrame({
    'Feature': X_train_all.columns,
    'Importance' : cbc_feature_importance
}).sort_values('Importance', ascending=False)

fig = px.bar(feature_importance_df.head(20), x='Feature', y='Importance', title='Top 20 CBC Feature Importance', text_auto=True)
fig.show()

"""### Conclusion: Feature Importance Hierarchy
The distribution of feature importance shows a clear hierarchy of influence contributing to the model's decision-making process:

* **Primary Driver**: `loan_percent_income` is the most dominant feature by a significant margin. This suggests that the relative financial burden of the loan compared to the applicant's earnings is the strongest predictor of default.

* **Economic Stability**: Factors such as `RENT`, `person_income`, and `loan_int_rate` follow closely. This indicates that the model heavily weighs the applicant's cash flow, housing situation, and the direct cost of the loan.

* **Secondary Factors**: `person_emp_length` and specific categories like `D` (credit grade) show moderate importance, while demographic factors like `person_age` have the least impact among the top 20 drivers.
"""